export type RestaurantLocation = {
  lat: number;
  lng: number;
};

export function googleMapsUrlFromCoords(lat: number, lng: number): string {
  return `https://www.google.com/maps?q=${lat},${lng}`;
}

/** True when empty or matches a URL auto-generated from pin coordinates. */
export function isAutoGeneratedMapLink(link: string): boolean {
  const trimmed = link.trim();
  if (!trimmed) return true;
  return /^https:\/\/(www\.)?google\.com\/maps\?q=-?\d+(?:\.\d+)?,-?\d+(?:\.\d+)?$/i.test(
    trimmed,
  );
}

export function locationFromRestaurant(
  latitude: number | null | undefined,
  longitude: number | null | undefined,
): RestaurantLocation | null {
  if (
    latitude == null ||
    longitude == null ||
    !Number.isFinite(latitude) ||
    !Number.isFinite(longitude)
  ) {
    return null;
  }
  return { lat: latitude, lng: longitude };
}
